---
title: "R Notebook"
output: html_notebook
---

```{r}
library(RcppSimdJson)
library(data.table)
library("lubridate")
library(tidyverse)
library(stringi)
library(scales)
```

```{r}
read_cbop <- function(file) {
  cbop_file <- readLines(file)
  cbop <- fparse(json = cbop_file[1])

  cbop_list <- list()
  for (i in 1:length(cbop)) {
    
      prac <- cbop[[i]]$danePracodawcy
      names(prac) <- cbop[[i]]$hash
      prac_df <-  rbindlist(prac, idcol = "hash")
      setnames(prac_df, names(prac_df)[-1], paste0("prac_", names(prac_df)[-1]))
      
      pozostaleDane <- rbindlist(cbop[[i]]$pozostaleDane)
      setnames(pozostaleDane, names(pozostaleDane), paste0("poz_", names(pozostaleDane)))
      
      warunkiPracyIPlacy <- rbindlist(cbop[[i]]$warunkiPracyIPlacy)
      setnames(warunkiPracyIPlacy, names(warunkiPracyIPlacy), 
               paste0("war_", names(warunkiPracyIPlacy)))
      
      prac_df <- cbind(prac_df, pozostaleDane, warunkiPracyIPlacy)
      
      prac_df[, ":="(typOferty = cbop[[i]]$typOferty,
                     czyWazna = cbop[[i]]$czyWazna,
                     statusOferty = cbop[[i]]$statusOferty)]
      cbop_list[[i]] <- prac_df
  }

  cbop_list_df <- rbindlist(cbop_list)
  cbop_list_df[, .SD, .SDcols = names(cbop_list_df) %like% "data|oferta"]
  cbop_list_df[, ":="(poz_dataPrzyjZglosz=dmy(poz_dataPrzyjZglosz),
                      poz_ofertaWaznaDo=dmy(poz_ofertaWaznaDo))]
  
  final_df <- cbop_list_df[  typOferty == "OFERTA_PRACY" & 
                             czyWazna == TRUE & 
                             war_kraj == "Polska" & 
                        (!is.na(prac_regon) | !is.na(prac_nip)) &
                          war_rodzajZatrudnienia %in% 
                              c("Umowa o pracę na czas określony",                                                        "Umowa o pracę na czas nieokreślony", 
                                "Umowa o pracę w zastępstwie", 
                                "Umowa o pracę na okres próbny",
                                "Umowa na czas wyk. określonej pracy")][
                          , ":="(prac_nip = str_remove_all(prac_nip, "-"),
                                 kod_pocztowy = str_extract(war_miejscePracy,
                                                            "\\d{2}\\-\\d{3}"))][
                            !prac_nip %in% c("0000000000", "1111111111")]

  final_df[, ":="(war_gmina = tolower(war_gmina), 
                  war_ulica=tolower(war_ulica),
                  war_miejscowosc=tolower(war_miejscowosc),
                  war_stanowisko=tolower(war_stanowisko))]
  final_df[, war_ulica:=str_replace(war_ulica,  "pl\\.", "plac ")]	
  final_df[, war_ulica:=str_replace(war_ulica,  "al\\.", "aleja ")]	
  final_df[, war_ulica:=str_replace(war_ulica,  "  ", " ")]	
  final_df[, war_ulica:=str_remove(war_ulica,  "^\\.|-$")]
  final_df[, ":="(war_gmina = str_remove(war_gmina, "m.st. "))]
  final_df[, kod_pocztowy:=str_remove(kod_pocztowy, "00-000")]
  final_df[kod_pocztowy == "", kod_pocztowy := NA]
  final_df[, poz_kodZawodu := str_remove(poz_kodZawodu, "RPd057\\|")]
  final_df[, poz_grupaZawodu := substr(poz_kodZawodu, 1, 1)]
  final_df[, prac_regon := substr(prac_regon, 1, 9)]
  final_df[, poz_dataUdostepnieniaOferty := dmy(poz_dataUdostepnieniaOferty)]

  return(final_df)
}
```

```{r}
#Chosen columns to keep
columns_to_keep <- c('file', 'hash', 'prac_osobaDoKontaktu', 'prac_nrTelefonu', 'prac_nip', 'prac_nazwaUrzeduPracy', 'prac_regon', 'poz_kodZawodu', 'poz_zawod', 'poz_grupaZawodu', 'poz_lWolnychMiejsc', 'poz_kodKategoriiOferty', 'poz_udostepnionoDoEURES', 'poz_dlaPoborowych', 'poz_ofertaDlaOsobZarej', 'poz_identyfikatorOferty', 'poz_lWolnychMiejscDlaNiepeln', 'poz_finansZPfron', 'poz_ofertaWaznaDo', 'poz_ofertaZgloszonaPrzez', 'poz_ofertaZgloszonaPrzezKodJednostki', 'poz_dataUdostepnieniaOferty', 'poz_dataPrzyjZglosz', 'war_dataZakonczeniaPracy', 'war_miejscePracyCzlonDrugi', 'war_zakresObowiazkow', 'war_opisOferty', 'war_rodzajZatrudnienia', 'war_miejscePracyCzlonPierwszy', 'war_lGodzinWMiesiacu', 'war_kodZmianowosci', 'war_wojewodztwo', 'war_kodWojewodztwa', 'war_ulica', 'war_powiat', 'war_kodPowiatu', 'war_zawod', 'war_gmina', 'war_opisWynagrodzenia', 'war_pracaWWolneDni', 'war_wynagrodzenieBrutto', 'war_nrBudynku', 'war_kodSystemuWynagradzania', 'war_nrLokalu', 'war_miejscePracy', 'war_lGodzinWTygodniu', 'war_stanowisko', 'war_dataRozpoczeciaPracy', 'war_wymiarEtatu', 'war_miejscowosc', 'war_zatrOdZaraz', 'war_kodMiejscowosci', 'war_pracaStala', 'war_wynagrodzenieBruttoZTypemStawki', 'war_zmianowosc', 'war_pracaTymczasowa', 'war_kodRodzajuZatrudnienia', 'kod_pocztowy')
```

```{r}
create_table <- function(cbop_year, files) {

  for (file in files) {
    cbop_year[[length(cbop_year)+1]] <- read_cbop(file)
  }
  
  files <- str_remove_all(files, '(data\\\\\\d+\\\\|_full.json)')
  
  names(cbop_year) <- basename(files)
  cbop_year <- rbindlist(cbop_year, idcol = "file")
  cbop_year$file <- ymd(cbop_year$file)
  
  cbop_year <- cbop_year[, ..columns_to_keep]

  return(cbop_year)
}
```

```{r}
remove_duplicates <- function(cbop_year) {
  
  vector_year_stat <- c()
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Identical job offers
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year,
                                               by=names(cbop_year)[names(cbop_year)
                                                                   !='file'], 
                                       fromLast = TRUE) == FALSE)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Spelling mistakes
  for (i in columns_to_keep) {
    if (is.character(cbop_year[[i]]) == TRUE) cbop_year[[i]] <-
    stri_trans_general(cbop_year[[i]], 'pl-ascii')
  }
  
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year,
                                               by=names(cbop_year)[names(cbop_year)
                                                                   !='file'], 
                                       fromLast = TRUE) == FALSE)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Prolonged job offers
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','poz_ofertaWaznaDo')], 
                                       fromLast = TRUE) == FALSE)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Actualised job offers - different start date
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','war_dataRozpoczeciaPracy')], 
                                       fromLast = TRUE) == FALSE)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Actualised job offers - different end date
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','war_dataZakonczeniaPracy')], 
                                       fromLast = TRUE) == FALSE)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Actualised job offers - different salary
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','war_wynagrodzenieBrutto',
                                                      'war_wynagrodzenieBruttoZTypemStawki')], 
                                       fromLast = TRUE) == FALSE)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))

  #Prolonged job offers and actualised job offers
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','poz_ofertaWaznaDo',
                                                      'war_dataRozpoczeciaPracy')], 
                                       fromLast = TRUE) == FALSE)
  
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','poz_ofertaWaznaDo',
                                                      'war_dataZakonczeniaPracy')], 
                                       fromLast = TRUE) == FALSE)
  
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','poz_ofertaWaznaDo',
                                                      'war_dataRozpoczeciaPracy',
                                                      'war_dataZakonczeniaPracy')], 
                                       fromLast = TRUE) == FALSE)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Job offers with different phone no.
  cbop_dupes <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','prac_osobaDoKontaktu',
                                                      'prac_nrTelefonu')], 
                                       fromLast = FALSE) == TRUE |
                                      duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','prac_osobaDoKontaktu',
                                                      'prac_nrTelefonu')], 
                                       fromLast = TRUE) == TRUE) %>% 
    select(hash, poz_lWolnychMiejsc, poz_lWolnychMiejscDlaNiepeln) %>% group_by(hash) %>%
    summarise(poz_lWolnychMiejsc = sum(poz_lWolnychMiejsc), 
              poz_lWolnychMiejscDlaNiepeln = sum(poz_lWolnychMiejscDlaNiepeln))
  
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','prac_osobaDoKontaktu',
                                                      'prac_nrTelefonu')], 
                                       fromLast = FALSE) == FALSE)
  
  for(i in cbop_dupes$hash) {
    cbop_year$poz_lWolnychMiejsc[cbop_year$hash == i] <-
      cbop_dupes$poz_lWolnychMiejsc[cbop_dupes$hash == i]
    cbop_year$poz_lWolnychMiejscDlaNiepeln[cbop_year$hash == i] <-
      cbop_dupes$poz_lWolnychMiejscDlaNiepeln[cbop_dupes$hash == i]
  }
  rm(cbop_dupes)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Job offers with different vacancies
  cbop_dupes <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','poz_lWolnychMiejsc',
                                                      'poz_lWolnychMiejscDlaNiepeln')], 
                                       fromLast = FALSE) == TRUE |
                                      duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','poz_lWolnychMiejsc',
                                                      'poz_lWolnychMiejscDlaNiepeln')], 
                                       fromLast = TRUE) == TRUE) %>% 
    select(hash, poz_lWolnychMiejsc, poz_lWolnychMiejscDlaNiepeln) %>% group_by(hash) %>%
    summarise(poz_lWolnychMiejsc = sum(poz_lWolnychMiejsc), 
              poz_lWolnychMiejscDlaNiepeln = sum(poz_lWolnychMiejscDlaNiepeln))
  
  cbop_year <- cbop_year %>% filter(duplicated(cbop_year, 
                                       by=names(cbop_year)[!names(cbop_year) %in% 
                                                    c('file','poz_lWolnychMiejsc',
                                                      'poz_lWolnychMiejscDlaNiepeln')], 
                                       fromLast = FALSE) == FALSE)
  
  for(i in cbop_dupes$hash) {
    cbop_year$poz_lWolnychMiejsc[cbop_year$hash == i] <-
      cbop_dupes$poz_lWolnychMiejsc[cbop_dupes$hash == i]
    cbop_year$poz_lWolnychMiejscDlaNiepeln[cbop_year$hash == i] <-
      cbop_dupes$poz_lWolnychMiejscDlaNiepeln[cbop_dupes$hash == i]
  }
  rm(cbop_dupes)
  vector_year_stat <- append(vector_year_stat, length(cbop_year$hash))
  
  #Add new column
  stats_tab <<- cbind(stats_tab, year = vector_year_stat)
  
  return(cbop_year)
}
```

```{r}
#Table to stats
stats_tab <- data.table(duplication_type = c('Base value', 'Identical', 'Spelling mistakes', 'Prolonged', 'Actualised - different start date', 'Actualised - different end date', 'Actualised - different salary', 'Prolonged and actualised', 'Different contact data', 'Different number of vacancies'))
```

```{r}
#2020
cbop_2020 <- list()
files <- Sys.glob('data\\2020\\*.json')
cbop_2020 <- create_table(cbop_2020, files)
cbop_2020 <- remove_duplicates(cbop_2020)
rm(files)
```

```{r}
#2021
files <- Sys.glob('data\\2021\\*.json') 

cbop_2021_1 <- list()
files_1 <- files[1:floor(length(files)/2)]
cbop_2021_1 <- create_table(cbop_2021_1, files_1)
cbop_2021_1 <- remove_duplicates(cbop_2021_1)

cbop_2021_2 <- list()
files_2 <- files[(1+floor(length(files)/2)):length(files)]
cbop_2021_2 <- create_table(cbop_2021_2, files_2)
cbop_2021_2 <- remove_duplicates(cbop_2021_2)

rm(files)
rm(files_1)
rm(files_2)

cbop_2021 <- rbindlist(list(cbop_2021_1, cbop_2021_2))
rm(cbop_2021_1)
rm(cbop_2021_2)

cbop_2021 <- remove_duplicates(cbop_2021)
```

```{r}
#2022
cbop_2022 <- list()
files <- Sys.glob('data\\2022\\*.json')
cbop_2022 <- create_table(cbop_2022, files)
cbop_2022 <- remove_duplicates(cbop_2022)
rm(files)
```

```{r}
#2020-2022 All
cbop_all <- rbindlist(list(cbop_2020, cbop_2021, cbop_2022))
cbop_all <- remove_duplicates(cbop_all)
```

```{r}
#Table with stats - n
colnames(stats_tab) <- c('duplication_type', '2020', '2021_1', '2021_2', '2021_s', '2022', 'all')

stats_tab[, '2021'] <- stats_tab[,'2021_1'] + stats_tab[,'2021_2'] - cumsum(rbind(stats_tab[1,'2021_s'], stats_tab[1:9,'2021_s']) - stats_tab[,'2021_s'])
stats_tab <- subset(stats_tab, select = -c(3,4,5))

stats_tab[, 'all'] <- stats_tab[,'2021'] + stats_tab[,'2020'] + stats_tab[,'2022'] - cumsum(rbind(stats_tab[1,'all'], stats_tab[1:9,'all']) - stats_tab[,'all'])

stats_tab <- stats_tab %>% select('duplication_type', '2020', '2021', '2022', 'all')

stats_tab <- rbind(stats_tab, cbind('duplication_type' = 'Sum of duplicates', stats_tab[1,2:5]-stats_tab[10,2:5]))

#Table with stats - %
stats_tab_p <- cbind(stats_tab[,1], rbind(stats_tab[1,2:5], stats_tab[1:10,2:5]) - stats_tab[,2:5])
stats_tab_p <- stats_tab_p[-c(1,2,11),]

stats_tab_p[,2:5] <- cbind(
  list(percent(round(as.numeric(unlist(prop.table(stats_tab_p[,2]))),digit = 5))),
  list(percent(round(as.numeric(unlist(prop.table(stats_tab_p[,3]))),digit = 5))),
  list(percent(round(as.numeric(unlist(prop.table(stats_tab_p[,4]))),digit = 5))),
  list(percent(round(as.numeric(unlist(prop.table(stats_tab_p[,5]))),digit = 5))))
```

```{r}
#Create RDS files
saveRDS(cbop_2020, file = "cbop_2020.rds")
saveRDS(cbop_2021, file = "cbop_2021.rds")
saveRDS(cbop_2022, file = "cbop_2022.rds")
saveRDS(cbop_all, file = "cbop_all.rds")
saveRDS(stats_tab, file = "stats_tab.rds")
saveRDS(stats_tab_p, file = "stats_tab_p.rds")
```